- name: create the ec2 instances
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-08e9a23d01ec385fb
    zone_id: AKIA4LBEIRKJTVI5436R
    domine_name: mandark.icu
    instances:
    # - backend
    # - mysql
    # - frontend

  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      image_id: "{{ ami_id }}"
      security_group: "{{ sg_id }}"
      region: us-east-1
      tags: 
        name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output
  
  - name: create route53 record
    amazon.aws.route53:
      state: present
      zone: "{{ domine_name }}"
      record: "{{ item.item }}.{{ domine_name }}"  #backend.mandark.icu
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"
  
  - name: create route53 record for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ domine_name }}"
      record: "{{ domine_name }}"  #mandark.icu
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      overwrite: true
    when: item.item == "frontend"
    loop: "{{ ec2_output.results }}"



