- name: setup mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql db
    ansible.builtin.package:
      name: mysql-server
      state: present
  
  - name: enable mysql db
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  
  - name: setup user password
    ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1