- name: setup patching server
  hosts: all
  become: yes
  tasks:
  - name: initiate patching
    ansible.builtin.dnf:
      name: kernel
      state: latest

  - name: initiating reboot
    ansible.builtin.reboot:
