- name: setup patching server
  hosts: epix_servers
  become: yes
  gather_facts: yes
  tasks:
  - name: checking kernel version with uname -r
    ansible.builtin.shell: uname -r
    register: kernel_info
  - name: print information
    ansible.builtin.debug:
        msg: "{{ kernel_info.stdout }}"
  
  # - name: Distribution
  #   debug: msg="{{ ansible_distribution }}"
  
  # - name: Distribution version
  #   debug: msg="{{ ansible_distribution_version}}"
  
  # - name: Distribution major version
  #   debug: msg="{{ ansible_distribution_major_version }}"
  
  - name: initiate patching
    ansible.builtin.dnf:
      name: kernel
      state: latest

  - name: initiating reboot
    ansible.builtin.reboot:
  
  - name: validating OS version post patching
    ansible.builtin.shell: uname -r
    register: kernel_info
  - name: print information
    ansible.builtin.debug:
        msg: "{{ kernel_info.stdout }}"
